export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_RESPONSE = 'FETCH_CURRENT_USER_RESPONSE';

export const FETCH_CURRENT_USER_PLAYLISTS_REQUEST = 'FETCH_CURRENT_USER_PLAYLISTS_REQUEST';
export const FETCH_CURRENT_USER_PLAYLISTS_RESPONSE = 'FETCH_CURRENT_USER_PLAYLISTS_RESPONSE';