export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_RESPONSE = 'FETCH_CURRENT_USER_RESPONSE';

export const FETCH_CURRENT_USER_PLAYLISTS_REQUEST = 'FETCH_CURRENT_USER_PLAYLISTS_REQUEST';
export const FETCH_CURRENT_USER_PLAYLISTS_RESPONSE = 'FETCH_CURRENT_USER_PLAYLISTS_RESPONSE';

export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_RESPONSE = 'CREATE_PLAYLIST_RESPONSE';

export const SHOW_CREATE_PLAYLIST_MODAL = 'SHOW_CREATE_PLAYLIST_MODAL';
export const HIDE_CREATE_PLAYLIST_MODAL = 'HIDE_CREATE_PLAYLIST_MODAL';

export const FETCH_NEW_RELEASES_REQUEST = 'FETCH_NEW_RELEASES_REQUEST';
export const FETCH_NEW_RELEASES_RESPONSE = 'FETCH_NEW_RELEASES_RESPONSE';

export const FETCH_ALBUM_REQUEST = 'FETCH_ALBUM_REQUEST';
export const FETCH_ALBUM_RESPONSE = 'FETCH_ALBUM_RESPONSE';

export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
export const FETCH_ARTIST_RESPONSE = 'FETCH_ARTIST_RESPONSE';