export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_RESPONSE = 'FETCH_CURRENT_USER_RESPONSE';

export const FETCH_FOLLOWING_STATUS_REQUEST = 'FETCH_FOLLOWING_STATUS_REQUEST';
export const FETCH_FOLLOWING_STATUS_RESPONSE = 'FETCH_FOLLOWING_STATUS_RESPONSE';

export const FOLLOW_REQUEST = 'FOLLOW_REQUEST';
export const FOLLOW_RESPONSE = 'FOLLOW_RESPONSE';

export const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST';
export const UNFOLLOW_RESPONSE = 'UNFOLLOW_RESPONSE';

export const CONTAIN_TRACKS_REQUEST = 'CONTAIN_TRACKS_REQUEST';
export const CONTAIN_TRACKS_RESPONSE = 'CONTAIN_TRACKS_RESPONSE';

export const SAVE_TRACKS_REQUEST = 'SAVE_TRACKS_REQUEST';
export const SAVE_TRACKS_RESPONSE = 'SAVE_TRACKS_RESPONSE';

export const REMOVE_SAVED_TRACKS_REQUEST = 'REMOVE_SAVED_TRACKS_REQUEST';
export const REMOVE_SAVED_TRACKS_RESPONSE = 'REMOVE_SAVED_TRACKS_RESPONSE';

export const FETCH_CURRENT_USER_PLAYLISTS_REQUEST = 'FETCH_CURRENT_USER_PLAYLISTS_REQUEST';
export const FETCH_CURRENT_USER_PLAYLISTS_RESPONSE = 'FETCH_CURRENT_USER_PLAYLISTS_RESPONSE';

export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_RESPONSE = 'CREATE_PLAYLIST_RESPONSE';

export const SHOW_CREATE_PLAYLIST_MODAL = 'SHOW_CREATE_PLAYLIST_MODAL';
export const HIDE_CREATE_PLAYLIST_MODAL = 'HIDE_CREATE_PLAYLIST_MODAL';

export const FETCH_NEW_RELEASES_REQUEST = 'FETCH_NEW_RELEASES_REQUEST';
export const FETCH_NEW_RELEASES_RESPONSE = 'FETCH_NEW_RELEASES_RESPONSE';

export const FETCH_ALBUM_REQUEST = 'FETCH_ALBUM_REQUEST';
export const FETCH_ALBUM_RESPONSE = 'FETCH_ALBUM_RESPONSE';

export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
export const FETCH_ARTIST_RESPONSE = 'FETCH_ARTIST_RESPONSE';

export const FETCH_SIMILAR_ARTISTS_REQUEST = 'FETCH_SIMILAR_ARTISTS_REQUEST';
export const FETCH_SIMILAR_ARTISTS_RESPONSE = 'FETCH_SIMILAR_ARTISTS_RESPONSE';

export const FETCH_ARTIST_TOP_TRACKS_REQUEST = 'FETCH_ARTIST_TOP_TRACKS_REQUEST';
export const FETCH_ARTIST_TOP_TRACKS_RESPONSE = 'FETCH_ARTIST_TOP_TRACKS_RESPONSE';

export const FETCH_ARTIST_ALBUMS_REQUEST = 'FETCH_ARTIST_ALBUMS_REQUEST';
export const FETCH_ARTIST_ALBUMS_RESPONSE = 'FETCH_ARTIST_ALBUMS_RESPONSE';
